name: install tool test

on:
  push:
    paths:
      - "action.yml"
      - ".github/workflows/test-install-tool.yml"
  pull_request:
    branches:
      - main
    paths:
      - "action.yml"
      - ".github/workflows/test-install-tool.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test_install_sccache:
    name: test-install sccache (latest + filename_format)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      result: ${{ steps.version.outcome || steps.install.outcome || 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        id: install
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: mozilla
          repository: sccache
          name: sccache
          extract: true
          tag_prefix: v
          version: latest
          os_linux: unknown-linux-musl
          arch_amd64: x86_64
          subdirectory: "{name}-v{version}-{arch}-{os}"
          filename_format: "{name}-v{version}-{arch}-{os}.{ext}"
          check_command: sccache --version
      - name: version
        id: version
        run: |
          # Should be in the path & things should be in the environment?
          sccache --version
          sccache --show-stats

  test_install_sccache_linux:
    name: test-install sccache (0.5.4 + linux_filename_format)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      result: ${{ steps.version.outcome || steps.install.outcome || 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        id: install
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: mozilla
          repository: sccache
          name: sccache
          extract: true
          tag_prefix: v
          version: 0.5.4
          os_linux: unknown-linux-musl
          arch_amd64: x86_64
          subdirectory: "{name}-v{version}-{arch}-{os}"
          filename_format_linux: "{name}-v{version}-{arch}-{os}.{ext}"
          check_command: sccache --version
      - name: version
        id: version
        run: |
          # Should be in the path & things should be in the environment?
          sccache --version
          sccache --show-stats

  test_status:
    name: Assert Tests Passed
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test_install_sccache
      - test_install_sccache_linux
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: test status
        id: test_status
        run: |
          function all_tests_pass() {
            expected="$#"
            counter=0
            while true; do
              case "$1" in
                success)
                  counter=$((counter+1))
                  shift;;
                *) break ;;
              esac
            done
            if [[ "$counter" == "$expected" ]]; then
              return 0
            else
              return 1
            fi
          }
          if all_tests_pass "${{ needs.test_install_sccache.outputs.result || 'failure'}}" \
              "${{ needs.test_install_sccache_linux.outputs.result || 'failure' }}"
          then
            echo "test_status=:thumbsup:" >> "$GITHUB_OUTPUT"
            echo ":thumbsup:" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "test_status=:thumbsdown:" >> "$GITHUB_OUTPUT"
            echo ":thumbsdown:" >> "$GITHUB_STEP_SUMMARY"
          fi
